theme-color: "#e9818c"
exclude: [".jekyll-cache", "azurepipelines*", "Gemfile*", ".gitignore", ".git", "README.md"]
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"