trigger:
- master

variables:
  JEKYLL_ENV: 'production'

pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- task: Docker@0
  displayName: Run Jekyll
  inputs:
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
     $(Build.SourcesDirectory):/srv/jekyll
     $(Build.ArtifactStagingDirectory):/srv/jekyll/_site
    containerCommand: 'jekyll build'
    detached: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
