trigger:
- master

variables:
  JEKYLL_ENV: 'production'

pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- task: CopyFiles@2
  displayName: 'Copy wedding.json'
  inputs:
    SourceFolder: '_dataTemplate/jamessandra'
    Contents: '*'
    TargetFolder: '_data/'
    OverWrite: true

- task: CacheBeta@0
  inputs:
    key: gembundle2 | $(Agent.OS) | ./Gemfile
    path: vendor/bundle
  displayName: Cache gems bundle

- script: gem install bundler
  displayName: 'gem install bundler'

- script:
   bundle install --retry=3 --jobs=4 --path vendor/bundle
  displayName: 'bundle install'

- script: |
   ls vendor/bundle/ruby -lah
   bundle exec jekyll build -d $(Build.ArtifactStagingDirectory) --config _config.yml,configs/jamessandra.yml
  displayName: 'jekyll build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
