trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- task: FileTransform@1
  displayName: 'wedding.json Transform'
  inputs:
    folderPath: '_data/'
    fileType: json
    targetFiles: wedding.json

- script: |
   gem install jekyll bundler
   bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
   bundle install
   jekyll build $(Build.ArtifactStagingDirectory)
  displayName: 'jekyll build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
