trigger:
- master

variables:
  JEKYLL_ENV: 'production'
  BUNDLE_PATH: $(Pipeline.Workspace)/.bundle
  GEM_HOME: $(Pipeline.Workspace)/.gem


pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- task: CopyFiles@2
  displayName: 'Copy wedding.json'
  inputs:
    SourceFolder: '_dataTemplate/jamessandra'
    Contents: '*'
    TargetFolder: '_data/'
    OverWrite: true

- task: CacheBeta@0
  inputs:
    key: gemsbundle | $(Agent.OS) | ./Gemfile
    path: $(BUNDLE_PATH)
  displayName: Cache gems bundle

- task: CacheBeta@0
  inputs:
    key: gems | $(Agent.OS) | ./Gemfile
    path: $(GEM_HOME)
  displayName: Cache gems

- script: |
   gem install jekyll bundler
   bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
   gem env
   ls $GEM_HOME
   ls $GEM_HOME/gems
   ls $GEM_HOME/bin
   ls $BUNDLE_PATH
   bundle exec jekyll build -d $(Build.ArtifactStagingDirectory) --config _config.yml,configs/jamessandra.yml
  displayName: 'jekyll build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
