trigger:
- master

variables:
  JEKYLL_ENV: 'production'

pool:
  vmImage: 'ubuntu-16.04'
  
steps:
- task: UseRubyVersion@0
  displayName: 'Use Ruby >= 2.4'

- task: CopyFiles@2
  displayName: 'Copy wedding.json'
  inputs:
    SourceFolder: '_dataTemplate/'
    Contents: wedding.json
    TargetFolder: '_data/'
    OverWrite: true


- script: |
   gem install jekyll bundler
   bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
   bundle install
   jekyll build -d $(Build.ArtifactStagingDirectory)
  displayName: 'jekyll build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
